### ISSUE TITLE
Buffer copy looses some single characters?

### ISSUE THREAD

**Issue by APN-Pucky** [APN-Pucky/mTUO#60]

**Comment by APN-Pucky** [comment]
![Screenshot_2024-04-27-13-58-47-725_de neuwirthinformatik alexander mtuo](https://github.com/APN-Pucky/mTUO/assets/4533248/48f65eca-fd50-4952-81a5-fd98c0ae4f58)

See last "Obsidian verlord"

**Comment by brzdek** [comment]
Noticed that, but disregarded as I did not think it impacts usability.

**Comment by APN-Pucky** [comment]
https://github.com/APN-Pucky/mTUO/commit/699a1c43a0ceef0afd68d99beadb40d389dbff2a fixes it
